project_id = "anwxyyjfqeilitduxzkg"

[functions.admin-create-user]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.admin-create-client]
verify_jwt = false

[functions.bank-sync]
verify_jwt = false

[functions.bank-webhook]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false
